apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "storage.fullname" . }}
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: 5Gi